/**
 * Batch 37 — statute quick-reference. Hand-written summaries of the
 * sections that dominate individual-tax practice. Plain summary for
 * students, a practice note for professionals. FY 2025-26 positions.
 */
export interface SectionRef {
  sec: string;
  title: string;
  plain: string;
  note: string;
  tags: string[];
}

export const SECTIONS: SectionRef[] = [
  { sec: "4", title: "Charge of income-tax", plain: "The charging section — income of the previous year is taxed in the assessment year at the Finance Act's rates.", note: "Every computation ultimately hangs off s.4; cite it when a notice questions the very basis of charge.", tags: ["basics"] },
  { sec: "10(13A)", title: "HRA exemption", plain: "House rent allowance is exempt to the extent of Rule 2A's min-of-three formula.", note: "Old regime only. Rent to a relative is fine if genuine — money trail + landlord declares it. PAN of landlord needed above ₹1L/yr rent.", tags: ["salary", "exemption", "old-regime"] },
  { sec: "16(ia)", title: "Standard deduction", plain: "Flat deduction from salary — ₹50,000 (old) / ₹75,000 (new regime, FY 2025-26).", note: "Applies to pension too (it's salary income). No documents needed — don't let clients forget it exists in BOTH regimes.", tags: ["salary", "deduction"] },
  { sec: "24(b)", title: "Home-loan interest", plain: "Interest on borrowed capital for house property — up to ₹2L for self-occupied (old regime).", note: "Let-out property: full interest deductible but s.71(3A) caps house-property LOSS set-off at ₹2L/yr; excess carries forward 8 years.", tags: ["house-property", "deduction", "old-regime"] },
  { sec: "44AD / 44ADA", title: "Presumptive taxation", plain: "Small businesses declare 6-8% of turnover, professionals 50% of receipts, as deemed income — no books needed.", note: "44ADA cap ₹75L (cash ≤5%). One advance-tax installment (15 Mar). Opting out after opting in bars 44AD re-entry for 5 years — advise carefully.", tags: ["business", "presumptive"] },
  { sec: "54 / 54F", title: "Capital-gains reinvestment relief", plain: "LTCG from house (54) or any asset (54F) is exempt if reinvested in a residential house within the window.", note: "54F needs FULL net consideration reinvested (proportionate otherwise). CGAS deposit before the s.139(1) due date preserves the claim — the most-missed step.", tags: ["capital-gains", "exemption"] },
  { sec: "80C", title: "The ₹1.5L basket", plain: "PPF, ELSS, EPF, LIC, principal repayment, tuition fees — capped at ₹1.5L together.", note: "Old regime only. 5-yr lock-in for tax-saver FDs; ELSS is 3. Stamp duty on a house purchase also qualifies — often forgotten.", tags: ["deduction", "old-regime"] },
  { sec: "80CCD(1B) / (2)", title: "NPS deductions", plain: "(1B): extra ₹50k self-contribution. (2): employer's contribution up to 10%/14% of basic — works in BOTH regimes.", note: "80CCD(2) is the only big lever left under the new regime — restructure CTC to use it. 14% ceiling now applies to private employees in the new regime.", tags: ["deduction", "nps", "new-regime"] },
  { sec: "80D", title: "Health insurance", plain: "₹25k self/family (+₹25k parents; ₹50k if senior). Preventive check-ups ₹5k within the limit.", note: "Old regime only. Cash premium kills the claim (except preventive). Multi-year policies: deduction is proportionate per year.", tags: ["deduction", "old-regime"] },
  { sec: "87A", title: "Rebate", plain: "Resident individuals: tax fully rebated up to ₹12L income (new regime, FY 2025-26); ₹5L (old).", note: "Marginal relief above ₹12L stops the cliff. Rebate does NOT apply against s.112A LTCG — a frequent computational error in returns.", tags: ["rebate", "new-regime"] },
  { sec: "111A", title: "STCG on listed equity", plain: "Short-term gains on listed shares/equity MF (STT paid) — flat 20% (post-Jul 2024 rate).", note: "Slab-rate basic exemption can absorb 111A gains for residents (s.111A(2)). Chapter VI-A deductions cannot be set against these gains.", tags: ["capital-gains"] },
  { sec: "112A", title: "LTCG on listed equity", plain: "Long-term listed-equity gains above ₹1.25L/yr taxed at 12.5% — no indexation.", note: "The ₹1.25L exemption is per year, not per scrip — harvest it annually. Grandfathering (FMV 31-1-2018) still matters for old holdings.", tags: ["capital-gains"] },
  { sec: "115BAC", title: "The new regime", plain: "Default concessional slabs; most exemptions/deductions (HRA, 80C, 80D…) are off the table.", note: "Salaried can switch every year in the return; business income gets ONE lifetime switch-back — document the 10-IEA election.", tags: ["new-regime", "basics"] },
  { sec: "139(1) / (4) / (5)", title: "Return filing & revision", plain: "Due 31 Jul (non-audit). Belated/revised returns until 31 Dec of the AY.", note: "Belated returns forfeit loss carry-forward (except house property) and the old-regime option. ITR-U allows updated returns up to 4 years — with additional tax.", tags: ["procedure"] },
  { sec: "143(1)", title: "Intimation", plain: "Automated processing — arithmetic errors, obvious inconsistencies, TDS mismatches.", note: "It's an intimation, not an assessment. 30 days to respond to adjustment proposals; rectification u/s 154 for mistakes apparent from record.", tags: ["procedure", "notice"] },
  { sec: "148 / 148A", title: "Reassessment", plain: "Income escaping assessment — notice after a show-cause procedure (148A).", note: "Time limits: 3 years standard, 5 years (post-2024 amendment) where escaped income ≥ ₹50L. Check the 148A(b) notice was actually served — procedural lapses win cases.", tags: ["procedure", "notice"] },
  { sec: "192 / 194 family", title: "TDS on salary & payments", plain: "Payer deducts tax at source — salary (192), interest (194A), contractor (194C), professional fees (194J), rent (194-I).", note: "Individuals paying rent > ₹50k/month must deduct 2% u/s 194-IB — tenants almost never know. Form 26AS/AIS reconciliation is the first step of every engagement.", tags: ["tds", "procedure"] },
  { sec: "234A", title: "Interest — late filing", plain: "1% per month (or part) on unpaid tax from the due date to filing.", note: "Runs only on the NET unpaid amount — if taxes were fully paid by the due date, late filing costs the s.234F fee but no 234A interest.", tags: ["interest", "notice"] },
  { sec: "234B", title: "Interest — advance-tax default", plain: "Paid less than 90% of assessed tax by 31 March → 1%/month from 1 April.", note: "Computed on assessed tax, so it grows through assessment — settle self-assessment tax fast. Rule 119A: round the base down to ₹100.", tags: ["interest", "notice"] },
  { sec: "234C", title: "Interest — deferment", plain: "Quarterly advance-tax shortfalls vs 15/45/75/100% — 1%/month for 3 months (1 for March).", note: "12%/36% safe harbour for the first two quarters. Capital gains/lottery arising mid-year: no 234C if paid in remaining installments.", tags: ["interest"] },
  { sec: "234F", title: "Late-filing fee", plain: "₹5,000 flat (₹1,000 if income ≤ ₹5L) for a belated return.", note: "It's a fee, not interest — no waiver jurisdiction. Payable even on nil-tax belated returns if filing was mandatory.", tags: ["procedure"] },
  { sec: "270A", title: "Penalty — under-reporting", plain: "50% of tax on under-reported income; 200% for misreporting.", note: "s.270AA immunity: pay the demand + don't appeal, within 30 days. Distinguish under-reporting from misreporting in every reply — the difference is 4×.", tags: ["penalty", "notice"] },
  { sec: "276CC", title: "Prosecution — failure to file", plain: "Wilful failure to furnish a return can be prosecuted — up to 7 years where tax evaded exceeds ₹25L.", note: "No prosecution if the return is filed before the AY ends or tax due (after TDS/advance) ≤ ₹10,000 — the classic defence checklist.", tags: ["penalty", "procedure"] },
  { sec: "89 / Rule 21A", title: "Arrears relief", plain: "Salary arrears taxed at the marginal rate of the year received get relief via spread-back recomputation.", note: "Form 10E BEFORE filing is mandatory — CPC disallows the claim without it, every single time.", tags: ["salary", "relief"] },
  { sec: "80GG", title: "Rent without HRA", plain: "Rent deduction when salary has no HRA component — least of ₹5k/month, 25% of income, rent − 10% of income.", note: "Old regime only; Form 10BA required; claimant (or spouse/minor child) must not own a house in the work city.", tags: ["deduction", "old-regime"] },
];
