/**
 * Rent-receipt generator (feature batch 5).
 * Salaried users claiming HRA need monthly rent receipts — this produces a
 * clean, print-ready sheet for any span of FY 2025-26, with the statutory
 * niceties handled (landlord PAN note when annual rent > ₹1L, revenue-stamp
 * note for cash payments > ₹5,000).
 */
import { PDFDocument, PDFFont, StandardFonts, rgb } from "pdf-lib";

const A4: [number, number] = [595.28, 841.89];
const BRAND = rgb(0.05, 0.35, 0.28);
const INK = rgb(0.13, 0.15, 0.19);
const MUTE = rgb(0.45, 0.48, 0.53);
const LINE = rgb(0.85, 0.87, 0.89);

const rs = (n: number) => "Rs. " + Math.round(n).toLocaleString("en-IN");
const clean = (s: string) => s.replace(/₹\s?/g, "Rs. ").replace(/[^\x20-\x7E -ÿ]/g, "").slice(0, 90);

export interface RentReceiptInput {
  tenantName: string;
  landlordName: string;
  landlordPan?: string;
  propertyAddress: string;
  monthlyRent: number;
  /** 1-12 months of FY 2025-26 starting April 2025. Default 12. */
  months?: number;
  paymentMode?: "bank transfer" | "UPI" | "cash" | "cheque";
}

const FY_MONTHS = [
  "April 2025", "May 2025", "June 2025", "July 2025", "August 2025", "September 2025",
  "October 2025", "November 2025", "December 2025", "January 2026", "February 2026", "March 2026",
];

export async function generateRentReceiptsPdf(input: RentReceiptInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const months = Math.max(1, Math.min(12, Math.floor(input.months ?? 12)));
  const mode = input.paymentMode ?? "bank transfer";
  const perPage = 3;

  for (let i = 0; i < months; i += perPage) {
    const page = doc.addPage(A4);
    const batch = FY_MONTHS.slice(i, Math.min(i + perPage, months));
    batch.forEach((month, j) => {
      const top = A4[1] - 40 - j * 265;
      // frame
      page.drawRectangle({ x: 36, y: top - 235, width: A4[0] - 72, height: 235, borderColor: LINE, borderWidth: 1 });
      page.drawRectangle({ x: 36, y: top - 40, width: A4[0] - 72, height: 40, color: BRAND });
      page.drawText("RENT RECEIPT", { x: 50, y: top - 27, size: 14, font: bold, color: rgb(1, 1, 1) });
      page.drawText(month, { x: A4[0] - 50 - bold.widthOfTextAtSize(month, 12), y: top - 26, size: 12, font: bold, color: rgb(0.85, 0.93, 0.9) });

      const row = (label: string, value: string, y: number) => {
        page.drawText(label, { x: 50, y, size: 10, font, color: MUTE });
        page.drawText(clean(value), { x: 190, y, size: 11, font: bold, color: INK });
      };
      row("Received from", input.tenantName, top - 70);
      row("Amount", `${rs(input.monthlyRent)} (rent for ${month})`, top - 95);
      row("Property", input.propertyAddress, top - 120);
      row("Payment mode", mode, top - 145);
      row("Landlord", input.landlordName + (input.landlordPan ? `   ·   PAN: ${input.landlordPan.toUpperCase()}` : ""), top - 170);

      page.drawLine({ start: { x: A4[0] - 230, y: top - 205 }, end: { x: A4[0] - 60, y: top - 205 }, thickness: 0.8, color: INK });
      page.drawText("Signature of landlord", { x: A4[0] - 218, y: top - 220, size: 9, font, color: MUTE });
      if (mode === "cash" && input.monthlyRent > 5000) {
        page.drawText("Affix revenue stamp (cash rent above Rs. 5,000)", { x: 50, y: top - 220, size: 8.5, font, color: MUTE });
      }
    });
    // footer notes on each page
    const notes: string[] = ["Generated by TaxSense AI · taxsense-ai.vercel.app"];
    if (input.monthlyRent * 12 > 100_000 && !input.landlordPan)
      notes.push("Note: annual rent exceeds Rs. 1,00,000 — your employer will need the landlord's PAN for HRA exemption.");
    notes.forEach((n, k) =>
      page.drawText(n, { x: 36, y: 30 - k * 12 + 12, size: 8, font, color: MUTE })
    );
  }
  return doc.save();
}
